### ISSUE TITLE
Execution Node Action<> or Func<>

### ISSUE THREAD

**Issue by Col45** [Wouterdek/NodeNetwork#27]
I think it would be useful to have associated Func<> or Action<> with the execution node types. I think this would be more in-line with how the Unreal Engine Blueprint system functions, where each execution node would propagate synchronously, performing its respective action and then returning to execute the next node. 

I didnt see any examples of this. I suppose it is possible currently to generate the sourcecode to do this via string building as in the current code example, but this seems clunky to me. 

Any insight on how this could be implemented or if it something you have thought about/ tried already?

**Comment by Wouterdek** [comment]
> I think this would be more in-line with how the Unreal Engine Blueprint system functions, where each execution node would propagate synchronously, performing its respective action and then returning to execute the next node.

Actually, Unreal blueprints are compiled from the node graph to a class before they are used in game. ([source](https://docs.unrealengine.com/en-us/Engine/Blueprints/TechnicalGuide/Compiler)) It does a better job of hiding it by providing visual feedback on what the nodes do in a debugger during execution, but under the hood it is compiled before usage. Some advantages to this strategy are easier debugging, performance optimization by a pre-existing compiler, less runtime overhead, greater portability of the resulting code, ...

That being said, if you don't like using strings you could consider using [expression trees](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/expression-trees/) instead. These can be both serialized and transformed into a runnable function at runtime. 

If you want to skip the intermediary step entirely and go straight to running code from nodes that is possible too. Instead of producing functions as strings, you would put the code straight into the node (or store a Func/Action). Each node of your node viewmodels could implement a common interface which provides a Run() method. Invoking this method on node A calls the Run() method on each of the nodes connected to its inputs to obtain the input values. It then calculates the result of node A and returns it. If you call Run() on the last node in the chain, the entire tree is recursively evaluated. Note that the inputs/outputs don't hold values, but only serve to connect functions.

If you decide that you want the functions to be run immediately as they are connected, then you would probably end up with something similar to the calculator example.

Does this answer your questions?

**Comment by Col45** [comment]
Thank you it does answer my question. I am assuming the Compile() methods are what gets called recursively? And in those methods there should be the entry point to executing additional code?

**Comment by Wouterdek** [comment]
That is correct.
