### ISSUE TITLE
Tutorial not working

### ISSUE THREAD

**Issue by NosWiz** [Wouterdek/NodeNetwork#32]
Hello,

I was trying to get the [tutorial project](https://wouterdek.github.io/NodeNetwork/cookbook/value_nodes) running, but the stated instructions did not work.
First, this:

> In your viewmodel definition, change
`var node1Input = new NodeInputViewModel();`
to
`var node1Input = new ValueNodeInputViewModel<string>();`

It took some time until I found out that it requires the NodeNetworkToolkit, which fixed the issue.

Later on, the tutorial states:

> To print the input value each time it changes, add the following code.
`node1Input.ValueChanged.Subscribe(newValue =>
    {
        Console.WriteLine(newValue);
    });`

But visual studio says that there is no definition for "ValueChanged". I did not find any information about it in the docs or anywhere else in the internet. I tried different namespaces, workarounds or other fixes, but did not manage to get it running.

Is the documentation maybe outdated? I did not find information about for which version it was written.

**Comment by Wouterdek** [comment]
> It took some time until I found out that it requires the NodeNetworkToolkit, which fixed the issue.

Well, the tutorial does say that it uses `NodeNetworkToolkit` a couple of lines above but I guess I could add another quick note there.

> Later on, the tutorial states:
> 
> > To print the input value each time it changes, add the following code.
> > `node1Input.ValueChanged.Subscribe(newValue =>     {         Console.WriteLine(newValue);     });`
> 
> But visual studio says that there is no definition for "ValueChanged". I did not find any information about it in the docs or anywhere else in the internet. I tried different namespaces, workarounds or other fixes, but did not manage to get it running.

`ValueChanged` is a public member of `ValueNodeInputViewModel` so you should be able to access it. ([Source code](https://github.com/Wouterdek/NodeNetwork/blob/master/NodeNetworkToolkit/ValueNode/ValueNodeInputViewModel.cs)). Maybe you used `NodeInputViewModel` instead of the `var` keyword?
