### ISSUE TITLE
Lots of nodes causing slowdown

### ISSUE THREAD

**Issue by PlatypusIV** [Wouterdek/NodeNetwork#35]
I have a large collection of nodes (1000+) and it seems to slow down heavily.
I think I might have made several mistakes along the way, but I wanted to know if there was a way to improve performance, that ive overlooked.

Still love the Project by the way.

**Comment by Wouterdek** [comment]
Yes, this is a known issue that is unfortunately not that easy to fix. If you profile your application you will probably see this is caused by a LayoutUpdated event handler in PortView. This is used to synchronize the position of the port with the viewmodel, which is then used to correctly draw connections. Its implementation is, frankly, inefficient. However, optimizing this is non-trivial as it is constrained by WPF which does not have functionality to track the transform of a view relative to another one. Last time I checked, the mechanisms to do this exist at least partially, but are not available publicly in the API.

The good news is, this is now more solvable than before now that WPF is open source. However, I do not currently have plans to engineer this fix. I am currently actively working on issue #24, which will allow the grouping of nodes into subnetworks. This mostly resolves this problem because grouping nodes reduces the node count in a single network.

**Comment by PlatypusIV** [comment]
> Yes, this is a known issue that is unfortunately not that easy to fix. If you profile your application you will probably see this is caused by a LayoutUpdated event handler in PortView. This is used to synchronize the position of the port with the viewmodel, which is then used to correctly draw connections. Its implementation is, frankly, inefficient. However, optimizing this is non-trivial as it is constrained by WPF which does not have functionality to track the transform of a view relative to another one. Last time I checked, the mechanisms to do this exist at least partially, but are not available publicly in the API.
> 
> The good news is, this is now more solvable than before now that WPF is open source. However, I do not currently have plans to engineer this fix. I am currently actively working on issue #24, which will allow the grouping of nodes into subnetworks. This mostly resolves this problem because grouping nodes reduces the node count in a single network.

Thank you for the quick and informative answer.
Sorry for troubling you and once again thanks for the aid.
