### ISSUE TITLE
Issue with Pharmacist.Common 1.5.3 package install

### ISSUE THREAD

**Issue by McallyD74** [Wouterdek/NodeNetwork#60]
I attempted to install NodeNetwork 4.2.0 targeting .NETFramework Version 4.7.2 and was met with the following error:

"Could not install package 'Pharmacist.Common 1.5.3'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.7.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author."

**Comment by Wouterdek** [comment]
Weird, I just tried creating a brand new C# WPF project with .NET 4.7.2 in VS19 and added NodeNetwork 4.2.0 through NuGet without any issues. 

Can you try creating a new project and adding just Pharmacist.Common?

**Comment by McallyD74** [comment]
Thank you for your help! I just tried to install 4.2.0 and Pharmacist.Common 1.5.3 with a fresh .NET 4.7.2 project. I got the same Error. I am using VS15 though, I should have mentioned that, do you think that's my issue?

**Comment by Wouterdek** [comment]
Nuget lists Pharmacist as a .NET standard package. I'm not sure, but that might trip up VS15, which is five years old by now. VS19 is worth a try. Also try creating a project without NodeNetwork and just Pharmacist. If that doesn't work, then that seems more like an issue for the [ReactiveUI](https://github.com/reactiveui/Pharmacist) team.

**Comment by KayakSnail** [comment]
VS15 won't like it (it didn't for me). The way round it is to manually download the package to your packages folder and edit the packages file with the correct information to include it. I forget exactly which fileit is. When you try to install the reactive items via nuget it sees that you have it already and skips the checks, which would otherwise fail.

**Comment by cedricmoers** [comment]
Hi, 
Unfortunately I experienced the same issue as mentioned above. But since this package looks really nice and promising, I spent a couple of hours and headaches to find a solution for this. Eventually this seems to work, with the help of this SO post: [https://stackoverflow.com/questions/46788323/installing-a-netstandard-2-0-nuget-package-into-a-vs2015-net-4-6-1-project](url) the Answer of Martin Ulrich:

```
Referencing .NET Standard 2.0 packages is supported using the following:

- NuGet 3.6.0 or higher for VS 2015 (from NuGet's download site - may not yet be listed as recommended latest)
- Install the ".NET Standard Support for Visual Studio 2015" from https://www.microsoft.com/net/download/core (NuGet in VS will also print a link to this in its output window).
There are a still few bugs when consuming .NET Standard 2.0 libraries, especially when mixing .NET Standard < 2.0 and 2.0 libraries but these updates give basic support.
```

Nuget did show a link, but it was different than mentioned in the post. 
Unfortunately I did not write it down and it was a direct download link, so it is not in my history, but the link is shown in the output window. Installing this as Admin and the latest Nuget version solved the issue. 

I also installed the latest .Net Core SDK just to be sure.

Now I can start playing with NodeNetwork!
