### ISSUE TITLE
Input and Output Ports on the Same Level

### ISSUE THREAD

**Issue by Sage-of-Mirrors** [Wouterdek/NodeNetwork#63]
Hello,

Would it be possible to force an output port to share the same Y coordinate with an input port and vice-versa? I would like to have the nodes chained in sequence like this: ![nodes](https://user-images.githubusercontent.com/6289769/79297602-3bb9f380-7ea4-11ea-8514-e03b81fb50e7.png)
Having the output so far down the side of the node causes some cleanliness issues, especially when the nodes have many inputs.

I would also like to ask how to use the execution-style port. I'm wandering blindly into ReactiveUI, and it's a bit intimidating!

Thanks!

**Comment by Wouterdek** [comment]
I believe the property you are looking for is [EndpointsStackingOrientation](https://wouterdek.github.io/NodeNetwork/api/api/NodeNetwork.Views.NodeView.html#NodeNetwork_Views_NodeView_EndpointsStackingOrientation) in the NodeView.

**Comment by Wouterdek** [comment]
Also, what do you mean exactly by "execution-style port". If you mean the Blueprint-style nodes as in the codegen example, you can find the source code for that example [here](https://github.com/Wouterdek/NodeNetwork/tree/master/ExampleCodeGenApp). Or do you mean something like the [shader editor](https://github.com/Wouterdek/NodeNetwork/tree/master/ExampleShaderEditorApp)?
If you mean the latter, as your screenshot suggests, I suggest looking at [this](https://github.com/Wouterdek/NodeNetwork/blob/master/ExampleShaderEditorApp/ViewModels/Nodes/Math2NodeViewModel.cs#L63). This is a simple node that takes in 2 floating point values and combines them using a math function.
Line 63 specifies declaritively that the result value changes when either of the 2 inputs change, and then uses the .Select to specify how the 2 values should be combined. Note that this is not operating on the floats themselves, but rather on the program code that will produce floats during execution. Similarly, the result node produces a program snippet like `a + b` rather than an actual value.

**Comment by bloxofcodes** [comment]
Hello Similar problem to Sage-of-Mirrors I want to make the output inline with input is that possible?

I checked EndpointsStackingOrientation but completely clueless?
