### ISSUE TITLE
Get Connected Nodes in order

### ISSUE THREAD

**Issue by MMJM** [Wouterdek/NodeNetwork#8]
Hi,

Is there a way to get the connected nodes in Order.

I have created a node that connects to multiple children and need to get those children in the top down order as seen in the UI.

Thanks

**Comment by Wouterdek** [comment]
Assuming you have a node with 1 output `o`, and that you want to get a list of all nodes connected to that output in vertical order:
```Csharp
var connectedNodes = 
    // Take all connections leaving from output o.
    o.Connections
    // Sort based on the Y-coordinate of the input port. (the other side of the connection)
    .OrderBy(c => c.Input.Port.CenterPoint.Y)
    // Select the input's parent node.
    .Select(c => c.Input.Parent)
    // A node with 2 inputs might have 2 connections to this output, so we should remove duplicates.
    .Distinct();
```

If you have multiple outputs, you can use `node.Outputs.SelectMany()` with the above query inside.

Is this what you are looking for?

**Comment by MMJM** [comment]
Thanks that does look like what I am after but I'm having trouble using it.

I've taken your ExampleCodeGenApp as a starting point for what I am doing as I am also trying to generate code so it seemed like a good starting point.

I'm currently trying to use the code above in this function.
`ExampleCodeGenApp.ViewModels.MainViewModel.MainViewModel()`

What I thought of was replacing this line of code
`var codeObservable = eventNode.OnClickFlow.Values.Changed.Select(_ => new StatementSequence(eventNode.OnClickFlow.Values));`

I thought this was along the right path but alas it doesn't work
```
          var codeObservable = eventNode.OnClickFlow.Connections.Changed.Select(_ => new StatementSequence(
                eventNode.OnClickFlow.Connections
                .OrderBy(c => c.Input.Port.CenterPoint.Y)
                .Select(c => (IStatement)c.Input.Parent)
                .Distinct()));

```
I know it has something to do with the casting in the select. I think I may want the c.Input.Values perhaps which is a List of IStatements but I'm just a little confused as to how to get the Models. 

Do you know where I'm going wrong with it here?

I'm new to the Reactive stuff and it looks like most of the work is done in the Node constructors. In there Observables are created and trigger off the work when things change. I'm also guessing, from what I see, there is no single model for a Node View. It appears models are attached to the Input and Output Ports via the Value property. Is my understanding all correct?

Thanks for your help.

**Comment by Wouterdek** [comment]
NodeNetwork provides the base views and viewmodels to create your own node editors. The base library provides the [basic structure](https://wouterdek.github.io/NodeNetwork/img/node_components.png) and observables to observe the state of the network, like for example which inputs are connected to which outputs. Specialized input/output subtypes exist in NodeNetworkToolkit package that monitor these connections and allow you to automatically assign values to outputs based on related inputs. The simplest usage of these can be found in the [ExampleCalculatorApp](https://github.com/Wouterdek/NodeNetwork/blob/master/ExampleCalculatorApp/ViewModels/Nodes/SumNodeViewModel.cs), where 2 numeric inputs are used to dynamically calculate and output the sum. Similarly, these value-based inputs/outputs are also used in the ExampleCodeGenApp to calculate expression/statement models based on other expression/statement models from inputs. The 'values' in this example are statements/expressions. Note that the real 'meat' of the application is in the inputs/outputs and the way they are related. The nodes are just containers.

So how to fix your code? Well, let's take a look at the original code:
```Csharp
// We define an observable that will output values of type StatementSequence.
IObservable<StatementSequence> codeObservable = 
    // eventNode.OnClickFlow is a ValueListNodeInputViewModel
    // It is an input that accepts multiple connections with different outputs.
    // It monitors these outputs and maintains a list of their associated values.
    // This observable will generate a value whenever this list of values changes.
    // This may be because a connection was added or removed, or because an
    // output decided to change its value.
    eventNode.OnClickFlow.Values.Changed
    // Whenever a value was added/removed/changed, we take the list of values (statements)
    // and generate a new StatementSequence that will execute these statements one by one.
    .Select(_ => 
        new StatementSequence(eventNode.OnClickFlow.Values)
    );
```

If I understand you correctly, you want to get these statements in the order of where the corresponding outputs are positioned vertically. This requires 2 changes: sorting the values, and making sure we recalculate whenever the order changes. The first one is fairly easy: I explained how to do it in my previous post. The second one, however, is much more difficult due to reactive extensions lacking proper support for collections. I'll try to write a working version later today.

**Comment by MMJM** [comment]
I'm trying to create a behaviour tree type structure. In my version I don't use the ValueList nodes but just ValueNodes. I can connect a parent node such as "Sequence" to multiple "Action" nodes using just the ValueNodes so that seems fine for my case. I've got the nodes etc in place and I can hook them up fine now I'm trying to hook up the code generation part for my needs.

I was however just using your ExampleCodeGenApp to get some understanding of how that all works. 

Thanks for the explanation in your last message about the code that exists currently. I also followed what your original suggestion was doing getting the position of nodes to order data. What I'm having trouble with is marrying up the two. Using the Connections to order the connected nodes I'm having troubles in understanding how I take that and push that in to a new statement sequence object. (forgetting the fact that it won't observe an order change for the moment)

Can you explain why you used a ValueListNodeInput as an Output in this example? I want to make sure I'm doing the right thing by just using a normal ValueNodeOutput to connect multiple nodes to an output.

Thanks for the continued assistance.

**Comment by Wouterdek** [comment]
> Can you explain why you used a ValueListNodeInput as an Output in this example? I want to make sure I'm doing the right thing by just using a normal ValueNodeOutput to connect multiple nodes to an output.

If you want an endpoint that accepts values, use an input. If you want an endpoint that creates values, use an output. By default, inputs don't accept multiple connections. So if you want to have an input that accepts multiple values, `ValueListNodeInput` is the class to use. In the example app, nodes have an output that generates an executable program statement. Since I want to be able to run multiple statements, I used a `ValueListNodeInput` to accept multiple statement values.

> What I'm having trouble with is marrying up the two. Using the Connections to order the connected nodes I'm having troubles in understanding how I take that and push that in to a new statement sequence object. (forgetting the fact that it won't observe an order change for the moment)

OK, so I wrote a piece of code that should do everything you want. Couple of notes:
- I use an extension method called `ObserveEach` that I created myself, and is included in `NodeNetwork.Utilities.ReactiveExtensions`. This helps dealing with changing lists of observables. In the current NuGet version, the signature of the method doesn't quite match up with what the code below needs. This is fixed in the master branch and I'll publish a new package version.
- This code is not as efficient as it potentially could be. Each time the output moves or its value changes, the list is recreated and resorted which has a O(N log N) time complexity. If the lists were cached and only reordered when the position changes, the time complexity would drop to O(1) for value updates and O(N) for position updates. However, without a proper reactive collections library this is hard to implement correctly. Furthermore, since the amount of connections is probably not that big this might not be such a problem.

```
var orderedInputValuesObservable = eventNode.OnClickFlow.Connections
                // Take each connection, and observe some properties of its output.
                // This automatically handles when connections are added/removed.
                .ObserveEach(con =>
                {
                    var output = (ValueNodeOutputViewModel<IStatement>)con.Output;
                    // Using merge, we get notifications when either one of the observables produces a value.
                    return Observable.Merge(
                        // Observe the output port position.
                        // Since we don't actually use the position value (we are only interested in the event),
                        // we select Unit.Default.
                        con.Output.WhenAnyValue(o => o.Port.CenterPoint).Select(_ => Unit.Default),
                        // Observe the output value.
                        output.Value.Select(_ => Unit.Default)
                    );
                })
                // When a position changes, create an ordered list 
                .Select(_ =>
                {
                    return eventNode.OnClickFlow.Connections
                        // Select the output from the connection.
                        .Select(con => con.Output)
                        .Cast<ValueNodeOutputViewModel<IStatement>>()
                        // Sort based on the Y-coordinate of the output port. (the other side of the connection)
                        .OrderBy(o => o.Port.CenterPoint.Y)
                        // Select the current value of the output.
                        .Select(o => o.CurrentValue);
                })
                // Create a new StatementSequence from the new list of statements.
                .Select(statementsList => new StatementSequence(statementsList));
```

**Comment by Wouterdek** [comment]
Modifying `Compile` won't work very well as at that point the layout information is already lost. At first look I see 2 ways to implement this:

- Modifying the code where the statements are created in the outputs of each node.
- Creating a custom input type that behaves like `ValueListNodeInputViewModel<T>` except it automatically sorts the values. Then you could use this type for each statement input and all would work as expected. You would need to add some code to line 41 that takes each list from the observable and sorts it.

**Comment by MMJM** [comment]
@Wouterdek 

That might be an idea. I shall try to create a custom input class.

I was struggling a bit yesterday regarding the generating of code in my project and why you had originally use the` ValueListNodeInputViewModel<T>`  on the output side of a node to kind of reverse the flow then it twigged as my code seemed to be going the wrong way. So I'm hoping I now understand that more :)
